config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # routes for web 
  resources :orders do 
    collection do
      post :filter
    end
    member do 
      post :change_status
    end
  end
  root "orders#index"
  
  # routes for the API's
  namespace :api, defaults: {format: :json} do
    resources :orders
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  
  STATUSES = ["pending", "delivered"]
  validates_presence_of :name
  validates :status, inclusion: {in: Order::STATUSES}
  scope :are_pending, -> {where(status: "pending")}
  scope :are_delivered, -> {where(status: "delivered")}
  
  def reverse_status
    self.status == "pending" ? "delivered" : "pending"
  end
  
  
end

app/controllers/api/base_controller.rb
module Api
class BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
  respond_to :json
  before_action :default_json

  def render_json(view_name)
    render view_name, formats: [:json], 
                     handlers: [:jbuilder], 
                       status: 200
  end
  
  def render_or_false(to_check, view)
    if to_check.present?
      render_json view
    else
      render json: false, status: 200
    end
  end
  
  protected

  def default_json
    request.format = :json if params[:format].nil?
  end

end
end

app/controllers/api/orders_controller.rb
module Api
class OrdersController < BaseController
 
  def create
    @order = Order.new(order_params)
    if @order.save
      render_or_false(@order, "api/orders/show")
    else
      render json: @order.errors.full_messages, status: 400 and return
    end
  end
  
  def update
    @order = Order.find_by_id(params[:id])
    if @order.present?
      if @order.update(order_params)
        render_or_false(@order, "api/orders/show")
      else
        render json: @order.errors.full_messages, status: 400 and return
      end
    end
  end
  
  def index
    @orders = Order.all
    render_or_false(@orders, "api/orders/index")
  end
 
  private
  
  def order_params
    params.require(:order).permit(:name, :description, :status)
  end
 
end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html
  
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all.order(updated_at: :desc)
  end
  
  def filter
    if params[:status] != "All"
      @orders = Order.where(status: params[:status])
    else
      @orders = Order.all
    end
    @orders = @orders.order(updated_at: :desc)
  end
  
  def change_status
    order = Order.find_by_id(params[:id])
    if order.present?
      order.status = order.reverse_status
      order.save
    end
    head :ok
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OrderFlow
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/orders/filter.js.haml
var orders = $("#{escape_javascript(render(partial: "orders/partials/orders_table"))}");
$(".orders_area").empty().append(orders)

app/views/orders/index.html.haml
%center
  %h3 Orders
.col-lg-10.col-lg-offset-1.margin_top_20
  
  .col-lg-12
    = form_tag filter_orders_path, method: :post, html: {multipart: :true}, remote: true, authenticity_token: true,  class: "filter_form" do
      .col-lg-3.margin_top_20.no_padding
        = select_tag "status", options_for_select(["All", "pending", "delivered"]), class: "form-control order_select"
    
  
  .col-lg-12.orders_area
    = render "orders/partials/orders_table"
    -# %table.table.table-striped.table-bordered.margin_top_20
    -#   %thead
    -#     %tr
    -#       %th Name
    -#       %th Description
    -#       %th Status
    -#       %th Last updated
    -#   %tbody
    -#     .order_area
    -#       - @orders.each do |order|
    -#         %tr
    -#           %td #{order.name}
    -#           %td #{order.description}
    -#           %td #{order.status}
    -#           %td #{time_ago_in_words(order.updated_at)} ago

:javascript
  window.order_flow.orders.filterOrders();
  window.order_flow.orders.refreshOrders();
  window.order_flow.orders.changeStatus();

app/views/orders/partials/_orders_table.html.haml
%table.table.table-striped.table-bordered.margin_top_20
  %thead
    %tr
      %th Name
      %th Description
      %th Status
      %th Last updated
  %tbody
    - if @orders.limit(1).present?
      - @orders.each do |order|
        %tr
          %td #{order.name}
          %td #{order.description}
          %td 
            = link_to order.status, "javascript:void(0);", title: "Change status", data: {orderId: order.id, confirm: "Are you sure you want to change the status to #{order.reverse_status}?"} , class: "change_status"
          %td #{time_ago_in_words(order.updated_at)} ago
    
    - else
      %tr
        %td No orders found
        %td 
        %td 
        %td 